### ISSUE TITLE
How to validate against other values?

### ISSUE THREAD

**Issue by jaysson** [tmpfs/async-validate#61]
I am trying to validate a token against a user account, fetched by email.

```javascript
const descriptor = {
        type: 'object',
        fields: {
            email: {
                type: 'string',
                required: true,
                test: function (cb) {
                    let regexp = /^[-a-z0-9~!$%^&*_=+}{\'?]+(\.[-a-z0-9~!$%^&*_=+}{\'?]+)*@([a-z0-9_][-a-z0-9_]*(\.[-a-z0-9_]+)*\.(aero|arpa|biz|com|coop|edu|gov|info|int|mil|museum|name|net|org|pro|travel|mobi|[a-z][a-z])|([0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}))(:[0-9]{1,5})?$/i;
                    if (!this.value.match(regexp)) {
                        this.raise('Invalid email address');
                    }
                    User.findOne({email: this.value}).then((user) => {
                        if (!user) {
                            this.raise('User not found');
                        }
                        cb();
                    }).catch((error) => {
                        throw error;
                    });
                }
            },
            token: {
                type: 'string',
                required: true,
                test: function (cb) {
                    // Need to get email here somehow
                    User.findOne({email: email, email_verification_token: this.value}).then((user) => {
                        if (!user) {
                            this.raise('Invalid token');
                        }
                        cb();
                    }).catch((error) => {
                        console.log(error)
                        this.raise(error.message)
                    });
                }
            }
        }
    };
```

I tried accessing `this.source` but it only contains the token while validating token. Email is removed after email validation.

In general, I can think of many use cases where you want to validate a field against another. For example, `end_date > start_date`.

How do I do this?

**Comment by tmpfs** [comment]
You should be able to access email via `this.source.email`, `this.source` contains the source *input* object being validated.

I just plugged it into a test and it is available as expected, hope it works for you.

See: https://github.com/tmpfs/async-validate#rule

Note that the state object is also available for passing data between rules so if you only wanted it available to the token validation you could put it in `this.state` and access it via `this.state` (potentially conditionally).

Let me know if this solves it for you. Ta.

**Comment by tmpfs** [comment]
Oops missed you point on `source`, double checking now...

**Comment by tmpfs** [comment]
Hmmm, it should not be removed from `source` - I've added a test case that verifies that the source contains the `email` field from a previous rule, see:

https://github.com/tmpfs/async-validate/commit/8e109fdef4a7ce04922109c6f5455089e3cf6199

**Comment by tmpfs** [comment]
If it's still not working let me see the output of `console.log(this)` in the token rule function.

**Comment by jaysson** [comment]
Seems to be working now.

I did npm update in the meanwhile.

**Comment by tmpfs** [comment]
Cool, thanks for letting me know. Closing as not an issue but re-open if you experience the same problem again.
